# yaml-language-server: $schema=https://promptkit.altairalabs.ai/schemas/latest/provider.json
apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: cartesia-friendly-woman
spec:
  id: cartesia-friendly-woman
  type: cartesia
  role: tts
  voice: 9121c0ae-12a6-4012-8158-6e4a72e6da91
  sample_rate: 24000
