# yaml-language-server: $schema=https://promptkit.altairalabs.ai/schemas/latest/provider.json
apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: elevenlabs-arnold
spec:
  id: elevenlabs-arnold
  type: elevenlabs
  role: tts
  voice: VR6AewLTigWG4xSOukaG
  model: eleven_v3
  sample_rate: 24000
