apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: mock-judge
spec:
  id: mock-judge
  type: mock
  model: mock-model
  defaults:
    temperature: 0.0
    max_tokens: 200
    top_p: 1.0
  additional_config:
    mock_config: {{ .project_name }}/providers/responses/mock-judge.yaml
