apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Provider
metadata:
  name: openai-gpt4o
spec:
  id: openai-gpt4o
  type: openai
  model: {{ .openai_model }}
  include_raw_output: false
  pricing:
    input_cost_per_1k: 0.00015
    output_cost_per_1k: 0.0006
  defaults:
    temperature: 0.7
    max_tokens: 1500
    top_p: 1.0
